# Generated by Django 5.0 on 2024-02-26 10:59

import apps.images.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='ai_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='blurhash_code',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='file_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='folder_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='image_url',
            field=models.ImageField(null=True, upload_to=apps.images.models.upload_to),
        ),
        migrations.AddField(
            model_name='image',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL),
        ),
    ]
