# Generated by Django 5.0 on 2024-02-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_image_ai_description_image_blurhash_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='folder_name',
        ),
        migrations.AddField(
            model_name='image',
            name='base_url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='category',
            field=models.TextField(null=True),
        ),
    ]
