# Generated by Django 5.0 on 2024-03-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_imagecollection_created_at_imagecollection_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecollection',
            name='name',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
